## Empty queue

# Try to dequeue an empty queue
/dequeue X
/catch empty

# It is empty
/empty YES

/empty NO
/catch return

## One item

/queue X

# It is not empty
/empty NO

/empty YES
/catch return

## Dequeue item

/dequeue X

# Empty again
/empty YES

/empty NO
/catch return

# Try dequeuing an empty queue again
/dequeue X
/catch empty

## Dequeue incorrect item

/queue X
/dequeue Y
/catch return

## Queue and dequeue many items

/empty YES
/queue X
/empty NO
/queue A
/empty NO
/dequeue X
/empty NO
/queue B
/empty NO
/queue C
/empty NO
/dequeue A
/empty NO
/dequeue B
/empty NO
/dequeue C
/empty YES