# Mess with argument vector

messwithargv 0
messwithargv 64 32
streq abcdef abcdef

# No error

noerror

# Expect and raise

expect 1 raise 1

raise 0

expect 2 raise 2
expect -1 raise -1
expect 0 noerror

# Expect recursion

expect 0 expect 0 expect 0 expect 0 expect 0 expect 0 expect 0 expect 0 noerror
expect 2 expect 1 expect 1 expect 1 expect 1 expect 1 expect 1 expect 1 raise 2
#      ^ Only catches here                                                    ^ Throws error 2

# Has command

hascommand "raise"
hascommand "expect"
hascommand "hascommand"

expect 1 hascommand "x"
expect 1 hascommand ""

# Asserts

assert 1 0

assert 0 0

assert 1 1

expect 1 assert 0 1

assert 1 2

expect 2 assert 0 2
expect 8 assert abc 1
expect 8 assert 1 abc

# Equal

streq "" ""
streq "a" "a"
streq "a" a
streq a "a"
streq a a

# Not equal

expect 1 streq a b
expect 1 streq " " ""
expect 1 streq "	" ""

# Length

strlen 0 ""
strlen 1 A
strlen 1 "A"
strlen 1 " "
strlen 3 ABC
strlen 3 "ABC"
strlen 3 " 	 "

expect 8 strlen abc abc

# Long commands

expect 2 good-day-sir-could-you-raise-an-error-for-me-please-i-really-need-that-error-to-be-raised 2

# Long arguments

strlen 78 reallylongargumentwithmorecharactersthantheargumentbufferofsixtyfourcharacters
strlen 234 reallylongargumentwithmorecharactersthantheargumentbufferofsixtyfourcharacterreallylongargumentwithmorecharactersthantheargumentbufferofsixtyfourcharacterssreallylongargumentwithmorecharactersthantheargumentbufferofsixtyfourcharacters

# Many arguments

sum 0
sum 0 0 0 0 0 0 0
sum 0 1 -1 2 -2 3 -3
sum 1 -1 1 -2 2 3 -2
sum 20 2 1 1 2 1 1 1 2 4 -2 1 1 2 1 1 1
sum 63 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1

# Command names

expect 1 RAISE 1
expect -3 r4153 -3

# At least x arguments

atleast0
atleast0 abc
atleast0 abc def

atleast1 abc
atleast1 abc def

# At most x arguments

atmost0

atmost1
atmost1 abc
