# No error

/noerror

# Expect and throw

/expect
/throw

# Has command

/hascommand "throw"
/hascommand "expect"
/hascommand "hascommand"

/expect
/hascommand "x"

/expect
/hascommand ""

# Asserts

/assert 1

/expect
/assert 0

/expect
/assert abc

# Equal

/streq "" ""
/streq "a" "a"
/streq "a" a
/streq a "a"
/streq a a

# Not equal

/expect
/streq a b

/expect
/streq " " ""

/expect
/streq "	" ""

# Length

/strlen 0 ""
/strlen 1 A
/strlen 1 "A"
/strlen 1 " "
/strlen 3 ABC
/strlen 3 "ABC"
/strlen 3 " 	 "

/expect
/strlen abc abc

# Long commands

/expect
/assertlongcmdcalled

/reallylongcommandwithmorecharactersthanthecommandbufferofsixtyfourcharacters
/assertlongcmdcalled

# Long arguments

/strlen 78 reallylongargumentwithmorecharactersthantheargumentbufferofsixtyfourcharacters
/strlen 234 reallylongargumentwithmorecharactersthantheargumentbufferofsixtyfourcharacterreallylongargumentwithmorecharactersthantheargumentbufferofsixtyfourcharacterssreallylongargumentwithmorecharactersthantheargumentbufferofsixtyfourcharacters

# Many arguments

/sumsixteen 16 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
